eureka:
  client:
#    自动刷新eureka配置
    refresh:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    
  instance:
    status-page-url:  ${server.servletPath}/info1
    home-page-url: ${server.servletPath}/health1
    
spring:
  application:
    name: eurekafeignclient
    
server:
  port: 9005  
 
 
  ## 日志级别设置  
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG 