eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    
  instance:
    status-page-url: ${server.servletPath}/info
    home-page-url: ${server.servletPath}/health
    
spring:
  application:
    name: eurekaarchaius

server:
  port: 7792     

## actuator/health
management:
  endpoint:
    health:
      show-details: always 


  ## 日志级别设置  
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
  