eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    
  instance:
    status-page-url: ${server.servletPath}/info
    home-page-url: ${server.servletPath}/health
    
spring:
  application:
    name: eurekaribbon

server:
  port: 7791     

## actuator/health
management:
  endpoint:
    health:
      show-details: always 
 
 ## ribbon 启用状态
 ## 每个名为client的Ribbon都有Spring Cloud维护的相应的子应用程序上下文。
 ## 此应用程序上下文在对命名客户机的第一个请求时被延迟加载。通过指定Ribbon客户端的名称，
 ## 可以将这种延迟加载行为改为在启动时急切地加载这些子应用程序上下文，如下例所示:
ribbon:
  eager-load:
    enabled: false
    clients: client1, client2, client3


## 日志级别设置  
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG 