eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    
  instance:
    status-page-url: ${server.servletPath}/infohystrix
    home-page-url: ${server.servletPath}/healthhystrix
    
spring:
  application:
    name: hystrixturbine

server:
  port: 7790     

## actuator/health
management:
  endpoint:
    health:
      show-details: always 
## 使用Hystrix Metrics Stream必备 
  endpoints:
    web:
      exposure:
        include:  hystrix.stream
turbine:
  app-config: eureka,HYSTRIX  # 需要监控的服务名，多个用,号分隔
  cluster-name-expression: "'default'"
 
  ## 日志级别设置  
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG