eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    
  instance:
    status-page-url:  ${server.servletPath}/info1
    home-page-url: ${server.servletPath}/health3
    
spring:
  application:
    name: consumer
  cloud:
    loadbalancer:
      ribbon: 
        enabled: true

server:
  port: 7788     
 
  ## 日志级别设置  
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG 